[package]
name = "lindera-dictionary"
version = "0.4.1"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>",
    "Jun Ohtani <johtani@gmail.com>"
    ]
edition = "2018"
description = "A morphological dictionary loader."
documentation = "https://docs.rs/lindera-dictionary"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/lindera/lindera-dictionary"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "directory", "loader"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"

lindera-core = { version = "0.4.1", path = "../lindera-core" }
