[package]
name = "lindera"
version = "0.1.6"
authors = ["Minoru Osuka <minoru.osuka@gmail.com>"]
edition = "2018"
description = "A Japanese Morphological Analysis Library."
homepage = "https://github.com/bayard-search/lindera"
repository = "https://github.com/bayard-search/lindera"
readme = "README.md"
keywords = ["japanese", "morphological", "analyzer", "tokenizer", "library"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.2"
encoding = "0.2.33"
lindera-core = "0.1.1"
lindera-ipadic = "0.1.6"
serde = {version="1.0.104", features = ["derive"] }
tantivy-fst = "0.2.1"

[dev-dependencies]
criterion = "0.3.1"

[profile.release]
lto = true

[[bench]]
name = "bench"
harness = false
