[package]
name = "lindera-ipadic-builder"
version = "0.4.0"
authors = [
    "Paul Masurel <paul.masurel@gmail.com>",
    "Minoru Osuka <minoru.osuka@gmail.com>"
    ]
edition = "2018"
description = "A Japanese morphological dictionary builder for IPADIC."
documentation = "https://docs.rs/lindera-ipadic-builder"
homepage = "https://github.com/lindera-morphology/lindera"
repository = "https://github.com/lindera-morphology/linderalindera-ipadic-builder"
readme = "README.md"
keywords = ["japanese", "morphological", "dictionary", "builder", "ipadic"]
categories = ["text-processing"]
license = "MIT"

[dependencies]
bincode = "1.2.1"
byteorder = "1.3.4"
clap = "2.33.0"
encoding = "0.2.33"
glob = "0.3.0"

lindera-fst = "0.1.0"

lindera-core = { version = "0.4.0", path = "../lindera-core" }

[[bin]]
name = "lindera-ipadic"
path = "src/main.rs"
